#!/usr/bin/env python
#-*- coding:utf-8 -*-

import sys
from src import options, log

#Prints program usage with all possible arguments
def printUsage():
    print 'USAGE: ./servicenow-cli [insert|get|reinsert] \
[incident|alert_event|ci] (parameters)'


#Main
if __name__ == '__main__':

    #No arguments? Print usage
    if len(sys.argv) == 1:
        printUsage()
        sys.exit(-1)

    #Checking number of arguments
    elif len(sys.argv) < 3:
        log.userMessage.error('Invalid number of arguments')
        printUsage()
        sys.exit(-1)

    #Checking if first argument is a valid option
    if (sys.argv[1] in options.options.keys()):
        #Checking if second argument is a valid option
        if (sys.argv[2] in options.options[sys.argv[1]].keys()):
            #It is, executing desired operation
            do_evaluate_option = options.options[sys.argv[1]][sys.argv[2]]
        else:
            #2nd argument invalid, exiting
            log.userMessage.error("Invalid second argument: %s" % sys.argv[2])
            printUsage()
            sys.exit(-1)
    else:
        #1st argument invalid, exiting
        log.userMessage.error("Invalid first argument: %s" % sys.argv[1])
        printUsage()
        sys.exit(-1)

    #Executing desired use case
    if (sys.argv[1] == 'reinsert'):
        do_evaluate_option()
    else:
        do_evaluate_option(sys.argv[3])

    sys.exit(0)
