version: 1
formatters:
  userMessage:
    format: '%(levelname)s: %(message)s'
  debugMessage:
    format: '%(asctime)s %(levelname)s: %(message)s'
  event:
    format: '%(asctime)s %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: userMessage
    stream: ext://sys.stdout
  alertEventsNotInsertedFile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: event
    filename: alertEventsNotInserted.log
    maxBytes: 8388608 # 8 MBytes
    backupCount: 0
  debugFile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debugMessage
    filename: debug.log
    maxBytes: 8388608 # 8 MBytes
    backupCount: 5
loggers:
  alertEventsNotInserted:
    level: DEBUG
    handlers: [alertEventsNotInsertedFile]
    propagate: no
root:
  level: DEBUG
  handlers: [console,debugFile]
