version: 1
formatters:
  userMessage:
    format: '%(levelname)s: %(message)s'
  debugMessage:
    format: '%(asctime)s %(levelname)s: %(message)s'
  event:
    format: '%(asctime)s %(message)s'
  pastEvent:
    format: '%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: userMessage
    stream: ext://sys.stdout
  alertEventsNotInsertedHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: event
    filename: alertEventsNotInserted.log
    maxBytes: 8388608 # 8 MBytes
    backupCount: 0
  alertEventsNotInsertedTempHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: event
    filename: alertEventsNotInserted.temp
    maxBytes: 8388608 # 8 MBytes
    backupCount: 0
  pastAlertEventsHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: pastEvent
    filename: alertEventsNotInserted.log
    maxBytes: 8388608 # 8 MBytes
    backupCount: 0
  pastAlertEventsTempHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: pastEvent
    filename: alertEventsNotInserted.temp
    maxBytes: 8388608 # 8 MBytes
    backupCount: 0
  debugFile:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: debugMessage
    filename: debug.log
    maxBytes: 8388608 # 8 MBytes
    backupCount: 5
loggers:
  alertEventsNotInserted:
    level: DEBUG
    handlers: [alertEventsNotInsertedHandler]
    propagate: no
  alertEventsNotInsertedTemp:
    level: DEBUG
    handlers: [alertEventsNotInsertedTempHandler]
    propagate: no
  pastAlertEvents:
    level: DEBUG
    handlers: [pastAlertEventsHandler]
    propagate: no
  pastAlertEventsTemp:
    level: DEBUG
    handlers: [pastAlertEventsTempHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [console,debugFile]
